### ISSUE TITLE
gs_edit_cells( ) is no longer working.

### ISSUE THREAD

**Issue by prasoonsrivas** [jennybc/googlesheets#293] opened 2017-01-30 07:58 UTC
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment] 2017-01-30 22:11
The R package googlesheets has not had an update in a long while, so can you be specific about what you mean by:

> as i update the package google-sheet

At the moment it's hard to say if the problem is really googlesheets or something else entirely. Can you use other functions such as `gs_ls()` or `gs_gap()`?

**Comment by prasoonsrivas** [comment] 2017-01-31 09:58
Hi jenny 
Apologize for not being specific.
Here is the scenario..
My R code pulls the data from flurry API and after prettifying , i upload the dataframe to my desired google sheet.
opsh <- gs_key("sheet_key", visibility = 'private', lookup = FALSE)
opsh <- opsh %>% gs_edit_cells(ws = "flurrydata_new",input=final_data, byrow= TRUE)
 it gives this error.

Error in function_list[[k]](value) : Bad Gateway (HTTP 502).


I am using R-3.3.2  Rstudio Version 0.99.903

Thanks

**Comment by jennybc** [comment] 2017-01-31 22:22
Can you use other functions such as `gs_ls()` or `gs_gap()`?

The error > 500 suggests it's on the Google side. Could anything be wonky with this particular sheet? Maybe try writing this data into new sheet as an experiment to start narrowing things down.

**Comment by prasoonsrivas** [comment] 2017-02-01 03:38
Hi Jenny thanks for your precious time.

ya am able to use both the function gs_ls( ) and gs_gap( ) properly in  the same sheet.
 As stated above by you, I also used different sheet but gives the same error. Error in function_list[k] : Bad Gateway (HTTP 502).

Thanks

**Comment by judecalvillo** [comment] 2017-03-05 20:27
Hey @prasoonsrivas. For what it's worth, it seems I had the exact same problem, and what helped me was to simply execute this from elsewhere (a remote Ubuntu instance). In other words, it appears to be a local environment issue (or 'local environment' as it relates to this particular function). Given how long the gs_edit_cells function takes to run/respond, I thought it might be a timeout issue, but it seems changing R's timeout Option doesn't really do anything to alleviate the problem (at least when changed to <= 300). 

Hope that helps! Let me know if you find an ultimate solution to this, as I'd love to be able to update my own affected sheet locally soon. 

-Jude C.

**Comment by GreenTomatoCars** [comment] 2017-04-25 14:43
Hi,

I'm having a similiar issue. We have been using a few scripts to update google sheets files, moved to a new user and environment, and since then its just been hanging with no errors.

Smaller or simpler tables do seem to work, but most are failing?

I can run the same script with different users and it still works.

**Comment by jennybc** [comment] 2017-04-25 15:06
@GreenTomatoCars can clarify this:

> I can run the same script with different users and it still works.

Is *only the user* different? Or, reference an earlier sentence in your comment, is the user **and environment** different?

I.e. can you be on the exact same machine and have consistently different success/failure results merely by switching the Google user?

**Comment by GreenTomatoCars** [comment] 2017-04-25 15:15
Hi, we are on the same machine, but using a different windows username, but that comes with a different r environment. So all packages and libraries have been installed separately for this user.

And we are using the same google user.

Does the clarify?

**Comment by jennybc** [comment] 2017-04-25 15:38
> Does the clarify?

I guess so. I just don't like the answer 😣.

I am hoping that the switch to the new API #247 will resolve some of these things w/o ever actually knowing what's going on. For example, I really suspect this issue may have nothing to do with the googlesheets package itself.

**Comment by alchenist** [comment] 2017-05-02 20:01
Also getting this error. Looks like it's specifically hanging on the POST to the batch request endpoint. Per Jude's reply above, this only seems to happen on a Windows machine; when I try the same call on a Linux VM, also w/ googlesheets v0.2.1, it seems to work. 

I'm not familiar with the internals, but maybe this is some underlying issue with libcurl/curl between OSs?

**Comment by jennybc** [comment] 2017-05-02 21:58
Maybe those affected should start to share system and session info to see if we spot something in common?

`devtools::session_info()` is my preferred function. If you don't have devtools, then `sessionInfo()`.

**Comment by alchenist** [comment] 2017-05-03 14:07
```
> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32
 ui       RTerm
 language (EN)
 collate  English_United States.1252
 tz       America/New_York
 date     2017-05-03

Packages -----------------------------------------------------------------------
 package      * version date       source
 assertthat     0.1     2013-12-06 CRAN (R 3.3.3)
 cellranger     1.1.0   2016-07-27 CRAN (R 3.3.3)
 curl         * 2.6     2017-04-27 CRAN (R 3.3.3)
 DBI            0.6-1   2017-04-01 CRAN (R 3.3.3)
 devtools       1.12.0  2016-06-24 CRAN (R 3.3.3)
 digest         0.6.12  2017-01-27 CRAN (R 3.3.3)
 dplyr          0.5.0   2016-06-24 CRAN (R 3.3.3)
 googlesheets * 0.2.1   2016-06-26 CRAN (R 3.3.3)
 httr         * 1.2.1   2016-07-03 CRAN (R 3.3.3)
 jsonlite       1.3     2017-02-28 CRAN (R 3.3.3)
 lazyeval       0.2.0   2016-06-12 CRAN (R 3.3.3)
 magrittr       1.5     2014-11-22 CRAN (R 3.3.3)
 memoise        1.0.0   2016-01-29 CRAN (R 3.3.3)
 openssl        0.9.6   2016-12-31 CRAN (R 3.3.3)
 purrr          0.2.2   2016-06-18 CRAN (R 3.3.3)
 R6             2.2.0   2016-10-05 CRAN (R 3.3.3)
 Rcpp           0.12.10 2017-03-19 CRAN (R 3.3.3)
 rematch        1.0.1   2016-04-21 CRAN (R 3.3.3)
 stringi        1.1.3   2017-03-21 CRAN (R 3.3.3)
 stringr        1.2.0   2017-02-18 CRAN (R 3.3.3)
 tibble         1.3.0   2017-04-01 CRAN (R 3.3.3)
 withr          1.0.2   2016-06-20 CRAN (R 3.3.3)
 xml2           1.1.1   2017-01-24 CRAN (R 3.3.3)
```

**Comment by michelledion** [comment] 2017-05-15 20:14
FWIW. I am sending data to googlesheets as part of a loop (1. query crossref API 2. clean data/assign to df 3. insert row of dataframe into googlesheet). In my experience, the loop initially ran for >3000 rows without interruption and then it started stopping with a 502 bad gateway error about every ~500 or so rows. And once restarted, it would have the 502 error again. After a couple of days of this, I rebooted the laptop + reopened RStudio with an earlier instance of the session, and it ran again really well for > 3000 loops. Now, with the next loop (with a different API query), it's returning the 502 frequently again. I do have an irregular pause programmed in the loop every 50 times, because I was thinking that I was getting a timeout from google. It's not timing out on those iterations of the loop, but the pause doesn't seem to help it either. 

``> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       America/Toronto             
 date     2017-05-15                  

Packages -----------------------------------------------------------------------
 package      * version  date       source         
 assertthat     0.1      2013-12-06 CRAN (R 3.3.0) 
 audio          0.1-5    2013-12-23 CRAN (R 3.3.0) 
 beepr        * 1.2      2015-06-14 CRAN (R 3.3.0) 
 bibtex         0.4.0    2014-12-31 CRAN (R 3.3.0) 
 bitops       * 1.0-6    2013-08-17 CRAN (R 3.3.0) 
 cellranger     1.1.0    2016-07-27 CRAN (R 3.3.0) 
 curl           2.3      2016-11-24 CRAN (R 3.3.2) 
 data.table   * 1.10.0   2016-12-03 CRAN (R 3.3.2) 
 DBI            0.5-1    2016-09-10 CRAN (R 3.3.0) 
 devtools       1.12.0   2016-06-24 CRAN (R 3.3.0) 
 digest         0.6.10   2016-08-02 CRAN (R 3.3.0) 
 dplyr          0.5.0    2016-06-24 CRAN (R 3.3.0) 
 googlesheets * 0.2.1    2016-06-26 CRAN (R 3.3.0) 
 htmltools      0.3.5    2016-03-21 CRAN (R 3.3.0) 
 httpuv         1.3.3    2015-08-04 CRAN (R 3.3.0) 
 httr           1.2.1    2016-07-03 CRAN (R 3.3.0) 
 jsonlite     * 1.1      2016-09-14 CRAN (R 3.3.0) 
 lazyeval       0.2.0    2016-06-12 CRAN (R 3.3.0) 
 magrittr       1.5      2014-11-22 CRAN (R 3.3.0) 
 memoise        1.0.0    2016-01-29 CRAN (R 3.3.0) 
 mime           0.5      2016-07-07 CRAN (R 3.3.0) 
 miniUI         0.1.1    2016-01-15 CRAN (R 3.3.0) 
 openssl        0.9.5    2016-10-28 CRAN (R 3.3.0) 
 plyr         * 1.8.4    2016-06-08 CRAN (R 3.3.0) 
 purrr          0.2.2    2016-06-18 CRAN (R 3.3.0) 
 qdapRegex    * 0.6.0    2015-12-13 CRAN (R 3.3.0) 
 R6             2.2.0    2016-10-05 CRAN (R 3.3.0) 
 rAltmetric   * 0.7.0    2017-04-19 CRAN (R 3.3.2) 
 Rcpp           0.12.8   2016-11-17 CRAN (R 3.3.2) 
 rcrossref    * 0.6.0    2016-11-09 CRAN (R 3.3.2) 
 RCurl        * 1.95-4.8 2016-03-01 CRAN (R 3.3.0) 
 RJSONIO      * 1.3-0    2014-07-28 CRAN (R 3.3.0) 
 shiny          1.0.0    2017-01-12 CRAN (R 3.3.2) 
 stringi        1.1.2    2016-10-01 CRAN (R 3.3.0) 
 stringr      * 1.2.0    2017-02-18 CRAN (R 3.3.2) 
 tibble         1.2      2016-08-26 CRAN (R 3.3.0) 
 withr          1.0.2    2016-06-20 CRAN (R 3.3.0) 
 XML          * 3.98-1.6 2017-03-30 cran (@3.98-1.)
 xml2           1.1.1    2017-01-24 CRAN (R 3.3.2) 
 xtable         1.8-2    2016-02-05 CRAN (R 3.3.0) 
>

**Comment by ayusharan** [comment] 2017-05-19 15:09
Facing the same issue: 

The error says: 
Error in function_list[[k]](value) : Bad Gateway (HTTP 502).

Other gs_xx functions are running smoothly. 

sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0        data.table_1.10.4  googlesheets_0.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     assertthat_0.2.0 mime_0.5         cellranger_1.1.0
 [5] R6_2.2.0         jsonlite_1.4     DBI_0.6-1        magrittr_1.5    
 [9] httr_1.2.1       stringi_1.1.5    rematch_1.0.1    lazyeval_0.2.0  
[13] curl_2.5         xml2_1.1.1       tools_3.2.2      readr_1.1.0     
[17] stringr_1.2.0    purrr_0.2.2      hms_0.3          httpuv_1.3.3    
[21] openssl_0.9.6    tibble_1.3.0

**Comment by katossky** [comment] 2017-06-07 14:29
Same problem on a Mac, without error message.

```
Session info ----------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Paris                
 date     2017-06-07                  

Packages --------------------------------------------------------------------------------------------------------
 package      * version    date       source                         
 assertthat     0.1        2013-12-06 CRAN (R 3.3.0)                 
 bindr          0.1        2016-11-13 cran (@0.1)                    
 bindrcpp     * 0.1        2016-12-11 cran (@0.1)                    
 cellranger     1.1.0      2016-07-27 CRAN (R 3.3.0)                 
 curl           2.3        2016-11-24 CRAN (R 3.3.2)                 
 DBI            0.6        2017-03-09 CRAN (R 3.3.2)                 
 devtools       1.12.0     2016-06-24 CRAN (R 3.3.0)                 
 digest         0.6.12     2017-01-27 CRAN (R 3.3.2)                 
 dplyr        * 0.5.0.9000 2017-03-21 Github (hadley/dplyr@2d7c5a2)  
 glue           0.0.0.9000 2017-03-20 Github (tidyverse/glue@099b283)
 googlesheets * 0.2.2      2017-05-07 CRAN (R 3.3.2)                 
 httr         * 1.2.1      2016-07-03 CRAN (R 3.3.0)                 
 jsonlite     * 1.3        2017-02-28 CRAN (R 3.3.2)                 
 lazyeval       0.2.0      2016-06-12 CRAN (R 3.3.0)                 
 magrittr       1.5        2014-11-22 CRAN (R 3.3.0)                 
 memoise        1.0.0      2016-01-29 CRAN (R 3.3.0)                 
 openssl        0.9.6      2016-12-31 CRAN (R 3.3.2)                 
 pkgconfig      2.0.0      2015-07-18 cran (@2.0.0)                  
 purrr          0.2.2      2016-06-18 CRAN (R 3.3.0)                 
 R6             2.2.0      2016-10-05 CRAN (R 3.3.0)                 
 Rcpp           0.12.10    2017-03-19 CRAN (R 3.3.2)                 
 rematch        1.0.1      2016-04-21 CRAN (R 3.3.0)                 
 rlang          0.0.0.9001 2017-03-21 Github (hadley/rlang@1eeb44d)  
 stringi        1.1.2      2016-10-01 CRAN (R 3.3.0)                 
 stringr        1.2.0      2017-02-18 CRAN (R 3.3.2)                 
 tibble         1.2        2016-08-26 CRAN (R 3.3.0)                 
 tidyr        * 0.6.1      2017-01-10 CRAN (R 3.3.2)                 
 withr          1.0.2      2016-06-20 CRAN (R 3.3.0)                 
 xml2           1.1.1      2017-01-24 CRAN (R 3.3.2)
```

**Comment by jennybc** [comment] 2017-06-07 15:50
Given the difficulty in pinpointing this problem and the fact that the error is >500, I'm not entirely sure what to do other than keep working on the reboot that wraps the new API. But I will see if I can reproduce it with a larger set of cells and `gs_edit_cells()`.

**Comment by Danteal56** [comment] 2017-06-16 20:43
Hi!

Same issue here. Is there any update?

cheers

**Comment by NicolasJupiter** [comment] 2017-06-20 10:09
Guys, similar issue: gs_edit_cells() throws this error:
Error in function_list[[k]](value) : Bad Request (HTTP 400).

What's a work around guys?

sessionInfo():
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 25 (Workstation Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2       googlesheets_0.2.2 sqldf_0.4-10       RSQLite_1.1-2      gsubfn_0.6-6       proto_1.0.0       
 [7] readr_1.1.0        dplyr_0.7.0        RForcecom_1.1      RPostgreSQL_0.4-1  DBI_0.6-1         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     bindr_0.1        xml2_1.1.1       magrittr_1.5     hms_0.3          R6_2.2.1        
 [7] rlang_0.1.1      rematch_1.0.1    stringr_1.2.0    httr_1.2.1       plyr_1.8.4       tcltk_3.3.3     
[13] tools_3.3.3      dbplyr_1.0.0     openssl_0.9.6    assertthat_0.2.0 digest_0.6.12    tibble_1.3.3    
[19] purrr_0.2.2.2    bitops_1.0-6     curl_2.6         RCurl_1.95-4.8   memoise_1.1.0    glue_1.1.0      
[25] stringi_1.1.5    cellranger_1.1.0 XML_3.98-1.7     jsonlite_1.4     chron_2.3-50

**Comment by GreenTomatoCars** [comment] 2017-06-20 10:13
Hey,
We were not able to figure out the reason.
It works only on earlier installed Rstudios even though both old and new have same version.
Daria

**Comment by sterfa02** [comment] 2017-06-20 21:50
I HAD this same issue but figured out a reason for it. A call to gs_edit_cells() would say that it had successfully updated the cells and computed the number of cells correctly but most times no cells in the Google sheet had actually be changed. So I decided to run a loop and use gs_edit_cells() a row at a time with my dataframe. What happened was that most rows showed up fine, but every so often a row was skipped. When I inspected those rows I found that I had "\v" character literals in my dataframe in those rows. Once I gsubbed them away, I was back in business.

**Comment by jennybc** [comment] 2017-06-21 12:54
I'm having a hard time piecing this all together. The errors 500 and above are on the Google side and the only possible thing we can do is to workarounds like try to upload in build, space requests out, etc.

The error from @NicolasJupiter is, however, different: Bad Request (HTTP 400). That's NOT on the Google side but should be taken as a legitimately malformed query. So it's probably not the same as what the others are seeing.

> It works only on earlier installed Rstudios even though both old and new have same version

RStudio should have nothing to do with this. Do you mean different versions of R? Knowing R (and OS) versions where you have success vs failure would be interesting.

@sterfa02 Interesting about the "\v"! Would you be willing to share a problematic sheet with me? It can be fake and small, but just demo the problem? So, same data in two sheets: one sheet with them and another without.

**Comment by sterfa02** [comment] 2017-06-21 14:09
I created a publicly editable Google Sheet. Feel free to test on it.
gsTest(data = data.frame(Data = "My\v Test Data") fails silently.
gsTest(data = data.frame(Data = "My Test Data") edits the sheet correctly.

`gsTest <- function(data){require(googlesheets); gs <- gs_url("https://docs.google.com/spreadsheets/d/1jBYwVwVwi0YewcB0KRz74o300KtyEBfDcpAi4JGkgmc/edit?usp=sharing", lookup = FALSE, visibility = "private"); gs_edit_cells(gs, ws = 1, input = data, col_names = TRUE)}`

According to https://msdn.microsoft.com/en-us/library/aa691087(v=vs.71).aspx, "\v" is a vertical tab so I imaging it's failing because googlesheets sets aside a specified range of cells to edit and part of the way through the edit, it tabs down to a cell it's not authorized to edit.

Other character literals actually work fine: "\r" and "\t" pass through and insert the correct behavior (carriage return and horizontal tab), while "\a" and "\b" make it fail silently (alert and backspace).

(After the sheet updates (or doesn't), this code throws a gs_lookup() error even though I have lookup set to FALSE. gs_edit_cells() doesn't have a lookup parameter but probably should since its second to last line is ss <- ss$sheet_key %>% gs_key(verbose = FALSE) performs a gs_lookup() by default, right?)

**Session Info**
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets_0.2.1

Thank you for such a useful package!

**Comment by GreenTomatoCars** [comment] 2017-06-22 00:07
Hi,

I mean we use R version 3.2.2 in different machines but get this error Bad Request (HTTP 400) only on one of them.
User are different but permissions are the same (we were assured by Admin).
Do you have any idea why could it happen?

**Comment by jennybc** [comment] 2017-06-22 03:11
> I mean we use R version 3.2.2 in different machines but get this error Bad Request (HTTP 400) only on one of them.
> User are different but permissions are the same (we were assured by Admin).
> Do you have any idea why could it happen?

This error is certainly compatible with trying to do something you don't have the permission for. It's very hard to say w/o seeing exact code.

**Comment by NicolasJupiter** [comment] 2017-06-22 03:58
Hey so, my error is different?! Great can you help me understand what's
wrong with my query then? Cuz I followed the docs properly..

Code:
gs_auth()
All_sheets <- as.data.frame(gs_ls())
Diff_sheet <- gs_title("Diff Sheet")
Act_diff_oms <- as.data.frame(TBL(sql_connection, SQL("select * from
current_act_table")))
Act_oms_diff <- gs_edit_cells(ss=Diff_sheet,ws="account_oms",input =
Act_diff_oms, anchor = "A1", col_names = TRUE, verbose = TRUE)


What I'm trying to do is read from database and write that date to me
Google sheet starting from cell A1. I can't replace the whole sheet because
I've placed some formulas from column R onwards.

What's the issue here guys?

**Comment by jennybc** [comment] 2017-06-22 04:06
What error do you get?

**Comment by jennybc** [comment] 2017-06-22 04:10
@NicolasJupiter I think you will have to experiment a bit to narrow things down: Can you definitely do one of my examples where you create a sheet and write to it (see the README or vignettes)? With your Diff_sheet sheet above, can you definitely create a new worksheet? If so, can you definitely write into a cell in this new worksheet? If all of that works, that would give a lot of information.

**Comment by NicolasJupiter** [comment] 2017-06-22 04:11
Error in function_list[k]<value> : Bad Request (HTTP 400).

Shared this and session info up top

**Comment by smmurphy** [comment] 2017-06-28 03:46
Hi All,

@jennybc thank you for a wonderful package that I use constantly! and thanks for everyone's very helpful posts concerning this issue.  I am getting the same HTTP 502 error as others above.  I was able to resolve this by running the same code on an Ubuntu server which solves the problem for me, but I have included my notes below in case they are helpful to others, or help to sort this out.

The example:

```
yo <- gs_new("yo")
yo <- gs_edit_cells(yo, input = head(iris), trim = TRUE)
gs_read(yo)

```  
Works perfectly well on the problem environment, but when I change it to...

```
googlesheets::gs_edit_cells(sc, input = head(iris,10), trim = TRUE)
Range affected by the update: "R1C1:R11C5"
Error in function_list[[k]](value) : Bad Gateway (HTTP 502).
```
I tried several versions of this wondering if it might be associated with permissions around changing the dimensions, or something like that, but as others have noted above it appears to be associated with the size of the update.  Starting with a fresh sheet, for example, doesn't help, nor does turning of trim, etc.  I get the same result by adding more columns to the input, e.g. using the `crimtab` data set.  

I have experienced this error exclusively on a networked windows 7 machine with the below system info.  I was not able to reproduce the problem on a Windows 10 machine, or on Ubuntu.

```
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-06-27                  

Packages -----------------------------------------------------------------------
 package          * version    date       source        
 assertthat         0.2.0      2017-04-11 CRAN (R 3.3.3)
 base             * 3.3.3      2017-03-06 local         
 bindr              0.1        2016-11-13 CRAN (R 3.3.3)
 bindrcpp         * 0.2        2017-06-17 CRAN (R 3.3.3)
 cellranger         1.1.0      2016-07-27 CRAN (R 3.3.3)
 colorspace         1.3-2      2016-12-14 CRAN (R 3.3.3)
 crayon             1.3.2      2016-06-28 CRAN (R 3.3.3)
 curl               2.7        2017-06-26 CRAN (R 3.3.3)
 data.table       * 1.10.4     2017-02-01 CRAN (R 3.3.2)
 datasets         * 3.3.3      2017-03-06 local         
 devtools           1.13.2     2017-06-02 CRAN (R 3.3.3)
 digest             0.6.12     2017-01-27 CRAN (R 3.3.3)
 dplyr              0.7.1      2017-06-22 CRAN (R 3.3.3)
 ggplot2          * 2.2.1      2016-12-30 CRAN (R 3.3.3)
 glue               1.1.1      2017-06-21 CRAN (R 3.3.3)
 googleAnalyticsR * 0.4.1      2017-06-19 CRAN (R 3.3.3)
 googleAuthR      * 0.5.1      2017-03-31 CRAN (R 3.3.3)
 googlesheets     * 0.2.2      2017-05-07 CRAN (R 3.3.3)
 graphics         * 3.3.3      2017-03-06 local         
 grDevices        * 3.3.3      2017-03-06 local         
 grid               3.3.3      2017-03-06 local         
 gridExtra        * 2.2.1      2016-02-29 CRAN (R 3.3.3)
 gtable             0.2.0      2016-02-26 CRAN (R 3.3.3)
 hms                0.3        2016-11-22 CRAN (R 3.3.3)
 htmltools          0.3.6      2017-04-28 CRAN (R 3.3.3)
 httpuv             1.3.3      2015-08-04 CRAN (R 3.3.3)
 httr             * 1.2.1      2016-07-03 CRAN (R 3.3.3)
 jsonlite           1.5        2017-06-01 CRAN (R 3.3.3)
 knitr            * 1.16       2017-05-18 CRAN (R 3.3.3)
 lattice            0.20-34    2016-09-06 CRAN (R 3.3.3)
 lazyeval           0.2.0      2016-06-12 CRAN (R 3.3.3)
 lubridate        * 1.6.0      2016-09-13 CRAN (R 3.3.3)
 magrittr           1.5        2014-11-22 CRAN (R 3.3.3)
 mailR            * 0.4.1      2015-01-14 CRAN (R 3.3.3)
 memoise            1.1.0      2017-04-21 CRAN (R 3.3.3)
 methods          * 3.3.3      2017-03-06 local          
 mime               0.5        2016-07-07 CRAN (R 3.3.2)
 munsell            0.4.3      2016-02-13 CRAN (R 3.3.3)
 pkgconfig          2.0.1      2017-03-21 CRAN (R 3.3.3)
 plyr               1.8.4      2016-06-08 CRAN (R 3.3.3)
 purrr              0.2.2.2    2017-05-11 CRAN (R 3.3.3)
 R.methodsS3        1.7.1      2016-02-16 CRAN (R 3.3.2)
 R.oo               1.21.0     2016-11-01 CRAN (R 3.3.2)
 R.utils            2.5.0      2016-11-07 CRAN (R 3.3.3)
 R6                 2.2.2      2017-06-17 CRAN (R 3.3.3)
 Rcpp               0.12.11    2017-05-22 CRAN (R 3.3.3)
 readr              1.1.1      2017-05-16 CRAN (R 3.3.3)
 rJava            * 0.9-8      2016-01-07 CRAN (R 3.3.2)
 rlang              0.1.1      2017-05-18 CRAN (R 3.3.3)
 RODBC            * 1.3-15     2017-04-13 CRAN (R 3.3.3)
 scales           * 0.4.1      2016-11-09 CRAN (R 3.3.3)
 shiny              1.0.3      2017-04-26 CRAN (R 3.3.3)
 stats            * 3.3.3      2017-03-06 local         
 stringi            1.1.5      2017-04-07 CRAN (R 3.3.3)
 stringr            1.2.0      2017-02-18 CRAN (R 3.3.3)
 testthat           1.0.2      2016-04-23 CRAN (R 3.3.3)
 tibble             1.3.3      2017-05-28 CRAN (R 3.3.3)
 tools              3.3.3      2017-03-06 local         
 utils            * 3.3.3      2017-03-06 local         
 withr              1.0.2      2016-06-20 CRAN (R 3.3.3)
 XLConnect        * 0.2-13     2017-05-14 CRAN (R 3.3.3)
 XLConnectJars    * 0.2-13     2017-05-14 CRAN (R 3.3.3)
 xml2               1.1.1      2017-01-24 CRAN (R 3.3.3)
 xtable             1.8-2      2016-02-05 CRAN (R 3.3.3)
 zoo              * 1.8-0      2017-04-12 CRAN (R 3.3.3)
```

**Comment by dsteinberg100** [comment] 2017-08-03 16:39
I am having a similar issue. gs_edit_cells is super slow on my desktop (PC), works completely fine on my laptop (Mac). For me it gets hung up on Range affected by the update for 10-20 minutes and finishes eventually. On my laptop it takes 10 seconds.

**Comment by jennybc** [comment] 2017-08-05 23:46
Just to check in. It's not that I don't care about this, it's that I don't know what to do about it. It's an intermittent phenomenon ... that also seems highly correlated with Windows.

Hence my "solution" is to keep working towards the switch to the Sheets API v3, where I hope performance will be less prone to such idiosyncrasies.

**Comment by dsteinberg100** [comment] 2017-08-06 14:09
That's understandable, I appreciate all the work you've done on this package.

**Comment by hexhead** [comment] 2017-10-05 15:46
I am having the 502 problem on Debian linux.

**Comment by hexhead** [comment] 2017-10-05 15:46
> sessionInfo() R version 3.4.0 (2017-04-21) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Debian GNU/Linux 9 (stretch)  Matrix products: default BLAS: /usr/lib/openblas-base/libblas.so.3 LAPACK: /usr/lib/libopenblasp-r0.2.19.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8         [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] googlesheets_0.2.2 dplyr_0.7.2        devtools_1.13.3     loaded via a namespace (and not attached):  [1] Rcpp_0.12.12     digest_0.6.12    withr_2.0.0      assertthat_0.2.0 cellranger_1.1.0 R6_2.2.2          [7] jsonlite_1.5     magrittr_1.5     httr_1.3.1       stringi_1.1.5    rlang_0.1.2      rematch_1.0.1    [13] curl_2.8.1       bindrcpp_0.2     xml2_1.1.1       tools_3.4.0      stringr_1.2.0    glue_1.1.1       [19] purrr_0.2.3      yaml_2.1.14      compiler_3.4.0   pkgconfig_2.0.1  memoise_1.1.0    openssl_0.9.6    [25] bindr_0.1        tibble_1.3.4
--
 
> | >
>

**Comment by hexhead** [comment] 2017-10-05 15:47
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets_0.2.2 dplyr_0.7.2        devtools_1.13.3   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     digest_0.6.12    withr_2.0.0      assertthat_0.2.0 cellranger_1.1.0 R6_2.2.2        
 [7] jsonlite_1.5     magrittr_1.5     httr_1.3.1       stringi_1.1.5    rlang_0.1.2      rematch_1.0.1   
[13] curl_2.8.1       bindrcpp_0.2     xml2_1.1.1       tools_3.4.0      stringr_1.2.0    glue_1.1.1      
[19] purrr_0.2.3      yaml_2.1.14      compiler_3.4.0   pkgconfig_2.0.1  memoise_1.1.0    openssl_0.9.6   
[25] bindr_0.1        tibble_1.3.4    
>

**Comment by jennybc** [comment] 2017-10-06 05:02
@hexhead Not that this helps you, but all errors 500 and above are on the server side. With any luck, this problem is intermittent.

**Comment by hexhead** [comment] 2017-10-06 14:44
Thanks for the feedback! I never got it going without the error (though I have before in another project), so I uploaded manually. I agree, and all commenters seem to have the same view that it is something going on with the Google side,.

**Comment by sanjmeh** [comment] 2018-01-29 12:02
Have read all the posts above. Excellent insights. And hats off to @jennybc who is so patiently trying to diagnose.
My issue is not the 502 server error but a very slow performance of `gs_edit_cells` (hangs for several minutes on a 7500 row 5 columns input data.table and ultimately we have to kill). For the same data `gs_upload` completes the job in 10-15 seconds. But of course we need `gs_edit_cells` to work because we need to update a worksheet of a preexisting googlesheet file. 
Is there a workaround of `gs_edit_cells`?

**Comment by jennybc** [comment] 2018-01-29 17:03
I'm sorry your specific task is slow and frustrating. Is there any chance that a temporary work around is to just update the whole file using a googledrive function, like `drive_update()`? That will preserve the file id. I know you only need to update one sheet, but ... if it's faster to update the content of the file *en masse*, that could get you unstuck.

I will definitely keep my eyes open for faster ways to do things like this in the new API.

**Comment by sanjmeh** [comment] 2018-01-29 18:04
I have installed googledrive package and will try to use the drive_update() function. I presume this package will allow multiple worksheets to be uploaded to a googlesheets file.. at least untill now I could not spot any function to load google sheet worksheets. But will continue to look.
Thanks

**Comment by jennybc** [comment] 2018-01-29 18:22
@sanjmeh `drive_update()` will update the content of any Drive file. That includes Sheets but there's nothing specific about Sheets. So it is still not exactly what you want, as you'll need to be uploading an entire workbook. I think it would obligate you to storing locally as ... Excel? Which you can write with writexl. But now that I say it all out loud, I realize it would be a very awkward workflow if your goal is to update one worksheet.

**Comment by sanjmeh** [comment] 2018-01-30 06:39
Yes, indeed :-) this route will be very awkward. The very purpose of using google sheets was to avoid excel.
In some other forum (SO or current thread) I read someone used a `for` loop to cycle through `gs_edit_cells` loading data chunk by chunk. I am thinking of using the same process as a workaround. Not sure if it will work in all situations.

These two are the main discussions happening on `gs_edit_cells` if we search across SO and GitHub. So these two (the server error and the hanging forever issue) seem to be the main problems in the otherwise wonderful `googlesheets` package.

**Comment by grantog** [comment] 2018-01-30 18:10
I am also running into `Error in function_list[[k]](value) : Bad Gateway (HTTP 502)` with gs_ws_new(). Also, when I try to run gs_new() with concurrently uploading a data table in the same statement, the command hangs. Not sure what to do here.

On a Mac, R Studio Version 1.1.383. I tried updating curl on the OS level via homebrew, tried updating all packages in R : (

**Closed** 2022-02-04 03:01 UTC
