### ISSUE TITLE
gs_perm_ls / _add not exported

### ISSUE THREAD

**Issue by jtaveras** [jennybc/googlesheets#201] opened 2016-02-10 21:03 UTC
gs_perm_ls and gs_perm_add shows up in the help docs, but the object does not exist.  It's the case for both the cran and install_github versions.  Are these functions available yet?

**Comment by jennybc** [comment] 2016-02-11 01:12
They are not (yet) exported. You can use them in the interim with the triple colon trick, i.e. `googlesheets:::gs_perm_ls()`. I am actively working on googlesheets now and formalizing/upgrading some of the Drive stuff is happening. Which includes this permission stuff, which is pure Drive API work (vs specific to Google Sheets).

I'm interested to know what you want them for and what sort of interface would make that easier. Because they are just in draft form now.

**Comment by jtaveras** [comment] 2016-02-16 23:44
Thanks for the tip, Jenny!  It worked.  To answer your question -- I'm creating a bunch of spreadsheets, each with their own groups of users.  I need to dynamically give each user group access to their respective sheets.  So the interface so far seems perfect for what I need.  Overall the package is great!

BTW, I tried it with send_email = FALSE and it still sent the email.  And this is probably out of your control, but it also issued a mobile notification, which I was hoping wouldn't happen.

**Comment by jennybc** [comment] 2016-02-17 20:16
Duplicate of #155 so will link these but close this one.

**Closed by jennybc** 2016-02-17 20:16 UTC
