### ISSUE TITLE
Endless loop of accessing sheets

### ISSUE THREAD

**Issue by brookezkeene** [jennybc/googlesheets#365] opened 2018-07-02 16:10 UTC
I have been using gs_title then gs_read_csv to access two Google Sheets at the beginning of my ui.R code. 

<img width="410" alt="screen shot 2018-07-02 at 12 09 59 pm" src="https://user-images.githubusercontent.com/32784028/42174613-f4413776-7df0-11e8-8493-38bd6316fb99.png">

This has been working perfectly up until now. For some reason, now my code keeps trying to access these two sheets until it hits a Too Many Requests error.  Do you have any idea why this may be happening?

<img width="483" alt="screen shot 2018-07-02 at 12 06 58 pm" src="https://user-images.githubusercontent.com/32784028/42174466-763d9e00-7df0-11e8-98fe-a51f3e38b426.png">

**Comment by jennybc** [comment] 2018-07-02 16:21
I don't know but I suspect the Shiny aspect of this is your best lead, as that is the most likely culprit re: a non-obvious reasons for re-executing the code. I can't think of anything in google sheets that can do this.

**Comment by brookezkeene** [comment] 2018-07-02 16:54
Ok, thank you for your help!

**Comment by jennybc** [comment] 2018-07-02 19:08
I'm going to close this but you're welcome to come back if you establish a root cause in the googlesheets package.

**Closed by jennybc** 2018-07-02 19:08 UTC
