### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [jennybc/googlesheets#381] opened 2019-05-14 15:12 UTC
Hi,

This is my first time using this library and I am finding an issue.
When I try to call gs_ls() or any other method, I am receiving this trace:

_Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
text/html_

Can anyone help me?

Thanks in advance.

**Comment by jennybc** [comment] 2019-05-14 15:23
It's hard to say what the problem is, but it is probably not encoding. This just indicates that the error message is coming back as html (aimed at someone using the browser), not as xml (aimed at someone calling an API).

googlesheets is sort of (unofficially) retired, btw, and will be succeeded by googledrive (already on CRAN) + googlesheets4 (available on GitHub).

What are you trying to do?

**Comment by DavidGarciaEstaun** [comment] 2019-05-14 15:57
Hi Jenny,

Thanks for your quick answer.
What I need to do are daily updates in a Google Sheets document that is used as a data source in Data Studio (dashboard).
I am going to review googlesheets4.

Thanks,
David.

**Comment by jennybc** [comment] 2019-05-14 16:54
Note that googlesheets4 can't *write* yet. Once I get [gargle](https://github.com/r-lib/gargle) onto CRAN (it's submitted), I'll probably do an early read-only release of googlesheets4.

If you are willing to update the whole Sheet, googledrive can do this today. See `drive_update()`.

And if you can explain more about your problem, there's probably a way to use googlesheets now. But I'd a specific narrative + code about exactly what you're doing.

**Comment by DavidGarciaEstaun** [comment] 2019-05-15 06:58
Hi Jenny,

Thanks for the information.
I try to get the Google Sheets file with the drive_get() and read_sheet methods and later I append some info and upload it with the drive_update() method but I am receiving this error:
_Error: Invalid dribble. These required column names are missing:
name
id
drive_resource_

I am going to do some testing but I think this should work...

Regards.

**Comment by jennybc** [comment] 2019-05-15 15:45
Again, these sorts of conversation are most productive when I can see exact code, in order of execution, and exact error messages.

But the above description of the error looks like you've added info to a data frame holding data to upload, but provided the data frame to `drive_update()` in a way that causes it to be interpreted as the dribble that specifies the target file id. It's impossible to say without seeing the code. I'm going to close this as it appears things are working or, even if not, your usage may be moving over to googledrive (not this package).

**Closed by jennybc** 2019-05-15 15:45 UTC
